# Generated by Django 3.0.4 on 2020-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounthistory_transaction_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingprogramparticipant',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='place_of_resident',
            field=models.CharField(choices=[('alexeyevskaya', 'Alexeyevskaya'), ('kievskaya', 'Kievskaya'), ('paveletskaya', 'Paveletskaya'), ('kremlin', 'Kremlin'), ('polis', 'polis'), ('rizhskaya', 'Rizhskaya'), ('sevastopolskaya', 'Sevastopolskaya'), ('smolenskaya', 'Smolenskaya'), ('depot', 'Depot'), ('lubyanka', 'Lubyanka'), ('unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savingprogramparticipant',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
    ]
