# Generated by Django 3.0.4 on 2020-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingprogramparticipant',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='savingprogramparticipant',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99),
        ),
    ]
