# Generated by Django 3.0.4 on 2020-07-01 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenfile',
            old_name='desription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='citizenfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
