# Generated by Django 3.0.4 on 2020-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReasonOfDeath',
        ),
    ]
